# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  host: 58.215.185.234
  port: 8066
  database: weibo_marketing
  pool: 5
  username: root
  password: amoeba

  shanghai:
    adapter: mysql2
    encoding: utf8
    host: 58.215.140.2
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: shanghai

  beijing:
    adapter: mysql2
    encoding: utf8
    host: 58.215.177.72
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: beijing

  guangdong:
    adapter: mysql2
    encoding: utf8
    host: 58.215.140.61
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: guangzhou

  zhejiang:
    adapter: mysql2
    encoding: utf8
    host: 58.215.160.211
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: zhejiang

  jiangsu:
    adapter: mysql2
    encoding: utf8
    host: 58.215.160.105
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: jiangsu

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  database: weibo_marketing
  pool: 5
  username:
  password:

production:
  adapter: mysql2
  encoding: utf8
  host: 58.215.185.234
  port: 8066
  database: weibo_marketing
  pool: 5
  username: root
  password: amoeba

  shanghai:
    adapter: mysql2
    encoding: utf8
    host: 192.168.1.52
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: shanghai

  beijing:
    adapter: mysql2
    encoding: utf8
    host: 58.215.177.72
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: beijing

  guangdong:
    adapter: mysql2
    encoding: utf8
    host: 192.168.14.111
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: guangzhou

  zhejiang:
    adapter: mysql2
    encoding: utf8
    host: 192.168.15.99
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: zhejiang

  jiangsu:
    adapter: mysql2
    encoding: utf8
    host: 192.168.15.37
    port: 3306
    database: weibo_marketing
    pool: 5
    username: root
    password: jiangsu

