production:
  solr:
    hostname: 192.168.20.148
    port: 8080
    master_hostname: 192.168.15.242
    master_port: 8080
    path: '/solr/'
    log_level: OFF
    auto_commit_after_request: false
    read_timeout: 500
    open_timeout: 500
  master_solr:
    hostname: 192.168.15.242
    port: 8080
    path: '/solr/'
    log_level: OFF
    auto_commit_after_request: false
    read_timeout: 500
    open_timeout: 500

development:
  solr:
    hostname: 192.168.20.148
    port: 8080
    master_hostname: 192.168.15.242
    master_port: 8080
    path: '/solr/'
    log_level: OFF
    auto_commit_after_request: false
    read_timeout: 500
    open_timeout: 500
  master_solr:
    hostname: 192.168.15.242
    port: 8080
    path: '/solr/'
    log_level: OFF
    auto_commit_after_request: false
    read_timeout: 500
    open_timeout: 500


test:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr/'
    log_level: OFF
  auto_commit_after_request: false


